//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiYa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiYaEntities : DbContext
    {
        public MiYaEntities()
            : base("name=MiYaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clarities> Clarities { get; set; }
        public virtual DbSet<Classifications> Classifications { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Cuts> Cuts { get; set; }
        public virtual DbSet<Kinds> Kinds { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Prefixes> Prefixes { get; set; }
        public virtual DbSet<RapScale_CtStone_Sizemms> RapScale_CtStone_Sizemms { get; set; }
        public virtual DbSet<Shapes> Shapes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
