//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiYa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderId { get; set; }
        public int Shape { get; set; }
        public int Color { get; set; }
        public int Clarity { get; set; }
        public int Cut { get; set; }
        public int Kind { get; set; }
        public int RapScale_CtStone_Sizemm { get; set; }
        public decimal Quantity { get; set; }
        public decimal TotalCt { get; set; }
        public int Status { get; set; }
        public System.DateTime DateOrder { get; set; }
        public string Note { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<decimal> carat { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Clarities Clarities { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Cuts Cuts { get; set; }
        public virtual Kinds Kinds { get; set; }
        public virtual RapScale_CtStone_Sizemms RapScale_CtStone_Sizemms { get; set; }
        public virtual Shapes Shapes { get; set; }
        public virtual Companies Companies { get; set; }
    }
}
